//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public short idOrder { get; set; }
        public string codeOrder { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public short IdPriority { get; set; }
        public short IdFactory { get; set; }
    
        public virtual Factory Factory { get; set; }
        public virtual Priority Priority { get; set; }
    }
}
