//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Filliations
{
    using System;
    using System.Collections.Generic;
    
    public partial class Filiation
    {
        public int idFiliation { get; set; }
        public string CodeFiliation { get; set; }
        public string DescFiliations { get; set; }
    }
}
