//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Routes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoutesEntities : DbContext
    {
        public RoutesEntities()
            : base("name=RoutesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlanetRoutes> PlanetRoutes { get; set; }
        public virtual DbSet<Planets> Planets { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<RouteTypes> RouteTypes { get; set; }
    }
}
